export const STATUSES = [
  'DRAFT', 'SUBMITTED', 'AI_CLASSIFIED', 'INITIAL_REVIEW', 'SITE_INSPECTION', 'VERIFIED', 'REJECTED', 'DUPLICATE',
  'ASSIGNED', 'IN_PROGRESS', 'WORK_COMPLETED', 'COMPLETION_VERIFIED', 'CLOSED', 'REOPENED',
] as const;
